# GitHub Dependabot Configuration
#
# Dependabot can maintain your repository's dependencies automatically.
#
# Documentation:
# - https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# - https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    labels:
      - dependencies
