# GitHub Dependabot Configuration
#
# Dependabot can maintain your repository’s dependencies automatically.
#
# Documentation:
# - https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
# - https://docs.github.com/en/code-security/dependabot/dependabot-version-updates
# - https://github.com/dependabot/dependabot-core/#readme

version: 2

updates:
  - package-ecosystem: pip
    directory: /
    ignore:
      - dependency-name: "bumpversion"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    groups:
      python-development:
        dependency-type: development
        exclude-patterns:
          - "bumpversion"
          - "pip"
          - "pip-tools"
          - "setuptools"
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore(deps):"
    labels:
      - dependencies
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    groups:
      github-actions-production:
        dependency-type: production
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore(deps):"
    labels:
      - dependencies
    open-pull-requests-limit: 5
