# GitHub Actions Workflow for Git Commit Linter

name: Git Commit Linter

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  git-commit-lint:
    name: Git Commit Linter
    uses: cordada/github-actions-utils/.github/workflows/git-commit-lint.yaml@master
